### ISSUE TITLE
Cannot run python code

### ISSUE THREAD

**Issue by garyramsgate** [brendan-w/python-OBD#117] opened 2018-09-10 20:23 UTC
Help.  I'm struggling to even run the Python-OBD code on my raspberry pi.
I suspect I'm missing something obvious.

I created a small python file with the following code:
import obd
connection=obd.OBD("/dev/rfcomm0")

However when I run the program I get the folling message:

Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 
Traceback (most recent call last):
  File "/home/pi/python-OBD-master/obd/test1.py", line 1, in <module>
    import obd
  File "/home/pi/python-OBD-master/obd/obd.py", line 36, in <module>
    from .__version__ import __version__
SystemError: Parent module '' not loaded, cannot perform relative import
>>> 

Any help would be gratefully appreciated.

**Comment by simontorres** [comment] 2018-09-24 15:20
I tried to reproduce your error and I get a slightly different one.
```shell

[simon@server obd]$ python test1.py 
Traceback (most recent call last):
  File "test1.py", line 1, in <module>
    import obd
  File "/data/user/Downloads/python-OBD-master/obd/obd.py", line 36, in <module>
    from .__version__ import __version__
ImportError: attempted relative import with no known parent package
```

Anyway, the problem is related to how python 3.x handles the imports (it is something I still don't fully understand) and I think it has to do with the execution path. It is not a good practice to execute a piece of code from within the package itself. Try moving the ``test1.py`` file to ``/home/pi/python-OBD-master`` and run it from there.

**Comment by alistair23** [comment] 2018-11-04 22:05
It sounds like the issue is fixed, I'm going to close this.

**Closed by alistair23** 2018-11-04 22:05 UTC
